/*
 * Copyright (C) 2026 by SkyWatch Space Applications Inc. http://www.skywatch.com
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option)
 * any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 */
package eu.esa.sar.iogdal.biomass;

import eu.esa.sar.commons.io.XMLProductDirectory;
import org.esa.snap.core.dataio.ProductReader;
import org.esa.snap.core.datamodel.Band;
import org.esa.snap.core.datamodel.MetadataElement;
import org.esa.snap.core.datamodel.Product;
import org.esa.snap.core.util.ProductUtils;
import org.esa.snap.core.util.SystemUtils;
import org.esa.snap.dataio.gdal.reader.plugins.GTiffDriverProductReaderPlugIn;
import org.esa.snap.engine_utilities.datamodel.AbstractMetadata;
import org.esa.snap.engine_utilities.datamodel.Unit;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * <b>EXPERIMENTAL / UNVERIFIED</b> reader for BIOMASS Level-2 products generated by the
 * open-source <a href="https://github.com/BioPAL/BioPAL">BioPAL</a> prototype, as opposed to
 * the official PDGS products (which {@link BiomassL2ProductDirectory} handles and which are
 * verified against real data).
 * <p>
 * BioPAL output differs fundamentally from the PDGS layout:
 * <ul>
 *     <li>No ESA {@code bio_fp_*.xml} main-product header — there is nothing to anchor the
 *         normal {@link XMLProductDirectory} machinery on, so {@link #readProductDirectory()}
 *         is a no-op and {@link #createProduct()} builds everything from the GeoTIFFs found.</li>
 *     <li>Products (AGB / Forest Height / Forest Disturbance) are written as GeoTIFFs on the
 *         <i>Equi7Grid</i> (a tiled equidistant projection), not WGS84 lat/lon COGs.</li>
 *     <li>Each run is written to a date-time-stamped output folder; configuration lives in an
 *         {@code Input_File.xml}, not an ESA MPH.</li>
 * </ul>
 * <p>
 * This reader therefore takes a deliberately <i>generic</i> approach: it scans the input tree for
 * GeoTIFFs whose names carry a BioPAL product token, opens each via GDAL (which supplies the
 * geocoding, Equi7 or otherwise), and exposes them as bands with synthesised abstracted metadata.
 * It is gated behind {@code -Dbiomass.biopal.reader=true} (see {@link BiomassProductReaderPlugIn})
 * so it can never claim a product unless explicitly enabled.
 * <p>
 * <b>TODO — confirm against a real BioPAL sample (none was available at implementation time):</b>
 * <ol>
 *     <li>Exact output folder tree and product file-naming convention (token positions).</li>
 *     <li>Whether Equi7 tiles of one product must be mosaicked rather than exposed as separate
 *         bands (this reader currently adds each tile as its own band, capped at {@link #MAX_BANDS}).</li>
 *     <li>Acquisition time / orbit / polarisation metadata source (BioPAL {@code Input_File.xml}).</li>
 *     <li>No-data conventions per product layer.</li>
 * </ol>
 */
public class BiomassBioPALProductDirectory extends XMLProductDirectory {

    private static final GTiffDriverProductReaderPlugIn READER_PLUGIN = new GTiffDriverProductReaderPlugIn();

    /** Safety cap so a tiled (many-Equi7-tile) run cannot explode into thousands of bands. */
    private static final int MAX_BANDS = 50;

    private String productName = "";

    private final List<ReaderData> bandProducts = new ArrayList<>();

    private static final class ReaderData {
        ProductReader reader;
        Product bandProduct;
        String bandName;
        String unit;
    }

    public BiomassBioPALProductDirectory(final File inputFile) {
        super(inputFile);
        this.productName = inputFile.getName();
    }

    /**
     * Classify a GeoTIFF filename into a BIOMASS L2 product layer, or {@code null} if it is not a
     * recognised BioPAL product raster. Shared with {@link BiomassProductReaderPlugIn} so detection
     * and parsing agree on what counts as a BioPAL product.
     *
     * @return {@code [bandBaseName, unit]} or {@code null}
     */
    static String[] classify(final String fileName) {
        final String n = fileName.toLowerCase();
        if (!(n.endsWith(".tif") || n.endsWith(".tiff"))) {
            return null;
        }
        if (n.contains("agb")) {
            return new String[]{"AGB", "t/ha"};
        }
        if (n.contains("forest_height") || n.contains("_fh") || n.contains("fh_") || n.contains("height")) {
            return new String[]{"Forest_Height", Unit.METERS};
        }
        if (n.contains("forest_disturbance") || n.contains("disturbance") || n.contains("_fd") || n.contains("fd_")) {
            return new String[]{"Forest_Disturbance", "flag"};
        }
        return null;
    }

    @Override
    public void readProductDirectory() {
        // BioPAL products carry no ESA XML header; nothing to pre-load.
    }

    @Override
    protected String getProductName() {
        return productName == null || productName.isEmpty() ? "BIOMASS_L2_BioPAL" : productName;
    }

    @Override
    protected String getProductType() {
        return "L2_BioPAL";
    }

    @Override
    protected String getRelativePathToImageFolder() {
        return getRootFolder();
    }

    @Override
    public void close() throws IOException {
        super.close();
        for (final ReaderData d : bandProducts) {
            if (d.bandProduct != null) d.bandProduct.dispose();
            if (d.reader != null) d.reader.close();
        }
    }

    @Override
    public Product createProduct() throws IOException {
        SystemUtils.LOG.warning("BIOMASS: opening '" + getBaseDir() + "' via the EXPERIMENTAL BioPAL reader " +
                "(-Dbiomass.biopal.reader=true). Output is best-effort and unverified against a reference product.");

        loadProductTiffs();
        if (bandProducts.isEmpty()) {
            throw new IOException("BIOMASS BioPAL: no recognisable AGB/FH/FD GeoTIFFs found under " + getBaseDir());
        }

        // Use the largest raster as the product scene; other layers attach with their own geocoding.
        ReaderData scene = bandProducts.get(0);
        for (final ReaderData d : bandProducts) {
            if ((long) d.bandProduct.getSceneRasterWidth() * d.bandProduct.getSceneRasterHeight()
                    > (long) scene.bandProduct.getSceneRasterWidth() * scene.bandProduct.getSceneRasterHeight()) {
                scene = d;
            }
        }

        final Product product = new Product(getProductName(), getProductType(),
                scene.bandProduct.getSceneRasterWidth(), scene.bandProduct.getSceneRasterHeight());

        final MetadataElement newRoot = buildMetadata();
        updateProduct(product, newRoot);

        addBands(product);

        // Scene geocoding from the scene COG (Equi7 or whatever GDAL parsed).
        if (product.getSceneGeoCoding() == null && scene.bandProduct.getSceneGeoCoding() != null
                && scene.bandProduct.getSceneRasterWidth() == product.getSceneRasterWidth()
                && scene.bandProduct.getSceneRasterHeight() == product.getSceneRasterHeight()) {
            ProductUtils.copyGeoCoding(scene.bandProduct, product);
        }
        if (product.getSceneGeoCoding() == null && product.getNumBands() > 0
                && product.getBandAt(0).getGeoCoding() != null) {
            product.setSceneGeoCoding(product.getBandAt(0).getGeoCoding());
        }

        return product;
    }

    private MetadataElement buildMetadata() {
        final MetadataElement root = new MetadataElement(Product.METADATA_ROOT_NAME);
        final MetadataElement absRoot = AbstractMetadata.addAbstractedMetadataHeader(root);
        AbstractMetadata.addOriginalProductMetadata(root);

        AbstractMetadata.setAttribute(absRoot, AbstractMetadata.MISSION, "BIOMASS");
        AbstractMetadata.setAttribute(absRoot, AbstractMetadata.PRODUCT, getProductName());
        AbstractMetadata.setAttribute(absRoot, AbstractMetadata.PRODUCT_TYPE, getProductType());
        AbstractMetadata.setAttribute(absRoot, AbstractMetadata.SAMPLE_TYPE, "DETECTED");
        AbstractMetadata.setAttribute(absRoot, AbstractMetadata.ProcessingSystemIdentifier, "BioPAL");
        setSLC(false);
        AbstractMetadata.setAttribute(absRoot, AbstractMetadata.srgr_flag, 1);
        AbstractMetadata.setAttribute(absRoot, AbstractMetadata.abs_calibration_flag, 1);
        return root;
    }

    private void loadProductTiffs() {
        final String[] allFiles;
        try {
            allFiles = getProductDir().listAllFiles();
        } catch (IOException e) {
            SystemUtils.LOG.warning("BIOMASS BioPAL: cannot list product directory: " + e.getMessage());
            return;
        }
        if (allFiles == null) {
            return;
        }

        for (final String relPath : allFiles) {
            if (bandProducts.size() >= MAX_BANDS) {
                SystemUtils.LOG.warning("BIOMASS BioPAL: band cap (" + MAX_BANDS + ") reached; remaining " +
                        "GeoTIFFs not loaded. Equi7 tile mosaicking is not yet implemented.");
                break;
            }
            final String name = new File(relPath).getName();
            final String[] meta = classify(name);
            if (meta == null) {
                continue;
            }
            try {
                final ReaderData d = new ReaderData();
                d.reader = READER_PLUGIN.createReaderInstance();
                d.bandProduct = d.reader.readProductNodes(getFile(relPath), null);
                if (d.bandProduct == null || d.bandProduct.getNumBands() == 0) {
                    SystemUtils.LOG.warning("BIOMASS BioPAL: could not open '" + relPath + "' — skipping.");
                    continue;
                }
                d.bandName = meta[0];
                d.unit = meta[1];
                bandProducts.add(d);
            } catch (Exception e) {
                SystemUtils.LOG.warning("BIOMASS BioPAL: failed to open '" + relPath + "': " + e.getMessage());
            }
        }
    }

    // ---- Unused XMLProductDirectory hooks: this reader drives everything from createProduct() ----
    @Override
    protected void addImageFile(final String imgPath, final MetadataElement newRoot) { /* not used */ }

    @Override
    protected void addGeoCoding(final Product product) { /* handled inline in createProduct */ }

    @Override
    protected void addTiePointGrids(final Product product) { /* no SAR tie-point grids for L2 */ }

    @Override
    protected void addAbstractedMetadataHeader(final MetadataElement root) { /* built in buildMetadata */ }

    @Override
    protected void addBands(final Product product) {
        final Set<String> usedNames = new LinkedHashSet<>();
        for (final ReaderData d : bandProducts) {
            final Band srcBand = d.bandProduct.getBandAt(0);
            final String bandName = uniqueName(usedNames, d.bandName);

            final Band band = new Band(bandName, srcBand.getDataType(),
                    srcBand.getRasterWidth(), srcBand.getRasterHeight());
            band.setUnit(d.unit);
            band.setSourceImage(srcBand.getSourceImage());
            if (srcBand.isNoDataValueUsed()) {
                band.setNoDataValueUsed(true);
                band.setNoDataValue(srcBand.getNoDataValue());
            }
            product.addBand(band);

            if (srcBand.getGeoCoding() != null) {
                ProductUtils.copyGeoCoding(srcBand, band);
            }
        }
    }

    private static String uniqueName(final Set<String> used, final String base) {
        if (used.add(base)) {
            return base;
        }
        int i = 2;
        String candidate;
        do {
            candidate = base + '_' + i++;
        } while (!used.add(candidate));
        return candidate;
    }
}
